<?php
	session_start();
?>
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8">
		<meta content="width=device-width",initial-scale=1">
		<title>Girls Hostel System</title>
		<link rel="stylesheet" href="bootstrap/css/bootstrap.min.css">
		<link rel="stylesheet" href="fontawesome/assets/css/font-awesome.min.css>
		<script type="text/javascript" src="js/jquery-2.1.0.min.js"></script>
		<script src="js/bootstrap.min.js"></script>
		<style>
		body{
			background-color:lavender;
		}
		.btn-toolbar{
			border: 3px solid darkblue;
			margin:15px;
			padding:5px;
			border-radius:4px;
			box-shadow: 0 0 30px ;
		}
		.btn-danger{
			font-color:black;
		}
		</style>
	
	</head>
	
	<body margin="25px">
			<nav role="navigation" class="navbar navbar-default">
				<div class="navbar-header">
					<button type="button" data-target="#navbarCollapse" data-toggle="collapse" class="navbar-toggle">
						<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					</button>
				<a href="home.phtml" class ="navbar-brand">Home</a>			
				</div>
				<div id=navbarCollapse class="collapse navbar-collapse">
					<ul class ="nav navbar-nav">
					<li class="active"><a href="http://jmi.ac.in/upload/hostel/hgr_manual_2014.pdf">About Us</a></li>
					<li><a href="http://jmi.ac.in/studyatjamia/hostel/latest/2" target="blank">Notifications</a></li>
					</ul>
					<ul class="nav navbar-nav navbar-right">
					<li><img src="/home/sarah/dbms_pro_final/logo.jpg"></li>
					<li ><a href="contact.html" ><i class="glyphicon glyphicon-phone-alt"></i>Contact Us</a></li></ul>
				</div>
			</nav>
			<div class="jumbotron vertical-center">
				<div class= "container">
			
					<form class="form-horizontal" role="form" action="" method="POST">		
        					<div class="form-group">
        						<label class="control-label col-sm-4" for="complaints">Complaint ID:</label>
       					   		<div class="col-sm-4">
            						<input type="text" name="compid" class="form-control" id="complaints" placeholder="Enter complaint ID to be edited" autofocus required>
         						</div>
        					</div>
						<div class="form-group">        
        						<div class="col-sm-offset-4 col-sm-5">
        					  	<button type="submit" class="btn btn-danger">Submit</button>
        					  	<button type="reset" class="btn btn-primary">Reset</button>
       							</div>
        					</div>
      					</form>
				</div>
			</div>
			<?php
	
	$dbdata='dbms_pro';
	$dbhost='localhost';
	$dbuser='root';
	$dbpass='dbms';
	
	$link=mysql_connect($dbhost,$dbuser,$dbpass);
	if(!$link)
	{
		 die('Could not connect:' . mysql_error());
	}
	$conc = mysql_select_db($dbdata,$link);
	if(!$conc )
	{
 		 die('Could not connect to db:' . mysql_error());
	}
	$v1=(int)$_POST["compid"];
	if(!$v1)
	{
		?><div class="alert alert-danger">
   			<a href="#" class="alert-link">No such complaintid present!!!</a>
		</div>
		<?php
	}
	else
	{
	$sql="UPDATE complaint set solved=1 where comp_id=$v1";
	?>
	<div class="alert alert-success">
   		<a href="#" class="alert-link">Success! Complaint Updated successfully</a>
	</div>
	<?php
	}
	?>
</body>
</html>
