<?php
		session_start();
?>
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8">
		<meta content="width=device-width",initial-scale=1">
		<title>Girls Hostel System</title>
		<link rel="stylesheet" href="bootstrap/css/bootstrap.min.css">
		<link rel="stylesheet" href="fontawesome/assets/css/font-awesome.min.css>
		<script type="text/javascript" src="js/jquery-2.1.0.min.js"></script>
		<script src="js/bootstrap.min.js"></script>
		<style>
		body{
			background-color:#CCFFFF;
		}
		</style>
	
	</head>
	<style>
		h1{
			font-family: "Times New Roman", Times, serif
			font-size:100%
		}
	</style>
	<body margin="25px" background="/home/sarah/Pictures/blue-backgrounds.png">
			<nav role="navigation" class="navbar navbar-default">
				<div class="navbar-header">
					<button type="button" data-target="#navbarCollapse" data-toggle="collapse" class="navbar-toggle">
						<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					</button>
				<a href="home.phtml" class ="navbar-brand">Home</a>			
				</div>
				
				<div id=navbarCollapse class="collapse navbar-collapse">
					<ul class ="nav navbar-nav">
					<li class="active"><a href="http://jmi.ac.in/upload/hostel/hgr_manual_2014.pdf">About Us</a></li>
					<li><a href="http://jmi.ac.in/studyatjamia/hostel/latest/2" target="blank">Notifications</a></li>
					</ul>
					<ul class="nav navbar-nav navbar-right">
					<li><img src="/home/sarah/dbms_pro_final/logo.jpg"></li>
					<li ><a href="contact.html" ><i class="glyphicon glyphicon-phone-alt"></i>Contact Us</a></li></ul>
				</div>
			</nav>
<?php
	
	$dbdata='dbms_pro';
	$dbhost='localhost';
	$dbuser='root';
	$dbpass='dbms';
	
	$link=mysql_connect($dbhost,$dbuser,$dbpass);
	if(!$link)
	{
		 die('Could not connect:' . mysql_error());
	}
	$conc = mysql_select_db($dbdata,$link);
	if(!$conc )
	{
 		 die('Could not connect to db:' . mysql_error());
	}
	$sn=1;
	$sql="Select * from late_table";
	$res=mysql_query($sql);
		if(!res)
		{
			die('sql error'.mysql_error());
		}
		?>
		<div class="panel panel-primary">
		<div class="panel-heading">
      			<h2 class="panel-title"><h1><b><u>LATE NIGHT: LIST</u></b></h1></h2>
		</div>
			<table class="table">
			<th>SerialNo.</th><th>Student Id.</th><th>Day</th><th>Reason</th>
		<?php
		while($row = mysql_fetch_array($res))
		{  
		echo "<tr><td>".$sn."</td><td>" .$row['stuid']."</td><td>" . $row['on_day'] ."</td><td>".$row['reason']. "</td></tr>";
		$sn++;
		} 
		?>
		</table>
		</div>
		<h2 align="center" >TOTAL:=:<?php echo --$sn?></h2>
		<?php
		mysql_close($link);
?>
</body>
</html>
